[workspace]
members = ["common"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.88"
version = "0.1.0"

[workspace.dependencies]
connectrpc = "0.8"
connectrpc-build = "0.8"
buffa = { version = "0.8", features = ["json"] }
buffa-types = { version = "0.8", features = ["json"] }
serde = { version = "1", features = ["derive"] }
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
common = { path = "common" }
