[package]
name = "common"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
test-support = ["dep:sea-orm", "dep:testcontainers"]

[dependencies]
connectrpc = { workspace = true }
buffa = { workspace = true }
buffa-types = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sea-orm = { workspace = true, optional = true }
testcontainers = { workspace = true, optional = true }

[build-dependencies]
connectrpc-build = { workspace = true }
