[package]
name = "common"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
connectrpc = { workspace = true }
buffa = { workspace = true }
buffa-types = { workspace = true }
serde = { workspace = true }

[build-dependencies]
connectrpc-build = { workspace = true }
