[package]
name = "crawler"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
common = { workspace = true }
connectrpc = { workspace = true, features = ["axum"] }
buffa = { workspace = true }
axum = { workspace = true }
regex = { workspace = true }
dom_smoothie = { workspace = true }
sha2 = { workspace = true }
spider = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["time"] }
